# data wrangling

In [2]:
# laod the library 
import pandas as pd

#create url 
url = "C:\\Users\\lenovo\\Downloads\\android-games (1).csv"

# laod data as a dataframe 
dataframe = pd.read_csv(url)

# shoe first 5 rows 
dataframe.head(5)

,rank,title,total ratings,installs,average rating,growth (30 days),growth (60 days),price,category,5 star ratings,4 star ratings,3 star ratings,2 star ratings,1 star ratings,paid
0,1,Garena Free Fire- World Series,86273129,500.0 M,4,2.1,6.9,0.0,GAME ACTION,63546766,4949507,3158756,2122183,12495915,False
1,2,PUBG MOBILE - Traverse,37276732,500.0 M,4,1.8,3.6,0.0,GAME ACTION,28339753,2164478,1253185,809821,4709492,False
2,3,Mobile Legends: Bang Bang,26663595,100.0 M,4,1.5,3.2,0.0,GAME ACTION,18777988,1812094,1050600,713912,4308998,False
3,4,Brawl Stars,17971552,100.0 M,4,1.4,4.4,0.0,GAME ACTION,13018610,1552950,774012,406184,2219794,False
4,5,Sniper 3D: Fun Free Online FPS Shooting Game,14464235,500.0 M,4,0.8,1.5,0.0,GAME ACTION,9827328,2124154,1047741,380670,1084340,False

In [36]:
# create new  dataframe 

# library 
import pandas as pd 

# create datarame 
dataframe = pd.DataFrame()

#add columns 
dataframe["name"] = ["jacky jackson" , "steven stevenson"]
dataframe["age"] = [38,25]
dataframe["driver"] = [True ,False]

# dataframe
dataframe

               name  age  driver
0     jacky jackson   38    True
1  steven stevenson   25   False

In [37]:
# we can append new row in dataframe 

new_person = pd.Series(["molly Money" , 40 , True],index = ["name","age","driver"])

In [38]:
# append row 
dataframe.append(new_person , ignore_index = True)

C:\Users\lenovo\AppData\Local\Temp\ipykernel_24160\3612231073.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe.append(new_person , ignore_index = True)

               name  age  driver
0     jacky jackson   38    True
1  steven stevenson   25   False
2       molly Money   40    True

In [39]:
# problem : want to view some characterstics of dataframe 

# we can di it by viewing first few rows using head 
#we can also take a look at the number of rows and colunm
dataframe.shape

(2, 3)

In [40]:
# we can describe statistics for any numeric columns using describe
dataframe.describe()

             age
count   2.000000
mean   31.500000
std     9.192388
min    25.000000
25%    28.250000
50%    31.500000
75%    34.750000
max    38.000000

In [41]:
# navigating data or slice of datafrfame 

dataframe.iloc[0]

name      jacky jackson
age                  38
driver             True
Name: 0, dtype: object

In [42]:
dataframe.iloc[1]

name      steven stevenson
age                     25
driver               False
Name: 1, dtype: object

In [43]:
new_data = {"name":["heer","koyali","ammu"] ,"age" :[34,56,23],"driver" : [False,True,True]}

In [44]:
dataframe1 = pd.DataFrame(new_data)
dataframe1

     name  age  driver
0    heer   34   False
1  koyali   56    True
2    ammu   23    True

In [46]:
df =  pd.concat([dataframe , dataframe1] , ignore_index = True)
df

               name  age  driver
0     jacky jackson   38    True
1  steven stevenson   25   False
2              heer   34   False
3            koyali   56    True
4              ammu   23    True

In [47]:
df.iloc[1:4]

               name  age  driver
1  steven stevenson   25   False
2              heer   34   False
3            koyali   56    True