# gradient descent

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("C:\\Users\\lenovo\\Downloads\\placement.csv")

In [5]:
df.head(10)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0
2  8.27          8.86       1
3  6.88          7.27       1
4  7.52          7.30       1
5  8.77          6.19       1
6  5.34          7.09       0
7  6.56          6.29       0
8  6.32          6.71       0
9  7.69          7.12       1

In [6]:
df.tail(5)

    cgpa  resume_score  placed
95  6.33          6.38       0
96  8.23          7.76       1
97  6.65          7.78       0
98  8.14          5.63       1
99  6.09          6.61       0

In [7]:
df.shape

(100, 3)

In [8]:
df.describe()

           cgpa  resume_score      placed
count  100.0000    100.000000  100.000000
mean     6.9422      6.930500    0.500000
std      1.1192      0.979608    0.502519
min      5.2700      4.950000    0.000000
25%      5.9800      6.190000    0.000000
50%      6.6200      7.055000    0.500000
75%      8.0450      7.640000    1.000000
max      9.4000      9.060000    1.000000

In [9]:
# we are plotting simple perceptron , which signifie , which student will plased or not 

# import required library
import  numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
sns.scatterplot(df["cgpa"],df["resume_score"],hue = df["placed"])

TypeError: scatterplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given

In [12]:
#conda update jupyter

In [13]:
x = df.iloc[:,0:2]
y = df.iloc[: , -1]

In [14]:
from sklearn.linear_model import Perceptron
p = Perceptron()

In [15]:
p.fit(x,y)

In [ ]:
p.coef_

In [17]:
p.intercept_

array([-25.])

In [18]:
#pip install mlxtend

In [19]:
import numpy as np
import pandas as pd

In [20]:
df = pd.read_csv("C:\\Users\\lenovo\\Downloads\\Churn_Modelling.csv")

In [21]:
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [22]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [23]:
print(df.shape)

(10000, 14)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [25]:
df.duplicated().sum()

0

In [26]:
df['Exited'].value_counts()

0    7963
1    2037
Name: Exited, dtype: int64

In [27]:
df["Geography"].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [28]:
# scaling : categorical data is not scalable .

In [29]:
df["Gender"].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [30]:
# we have to drop categorical columns : preparing for ANN
df.drop(columns = ["RowNumber","CustomerId","Surname"] , inplace =True)

In [31]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [32]:
df = pd.get_dummies(df,columns = ["Geography","Gender"],drop_first = True)

In [33]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0




get_dummies is a function provided by the pandas library in Python that is used for one-hot encoding categorical variables. One-hot encoding is a technique used to convert categorical data (data with discrete, non-numeric values) into a binary matrix (0s and 1s) so that it can be used as input for machine learning algorithms.

* If inplace=True: The method will modify the original DataFrame in place, and it will not return a new DataFrame. The changes will be applied directly to the DataFrame, and you don't need to assign the result to a new variable.
* When drop_first=True, :

the function omits the first category level for each categorical feature, resulting in n-1 dummy columns for a categorical column with n unique categories.

In [34]:
X = df.drop(columns = ["Exited"])

In [35]:
y = df["Exited"]

In [36]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0

In [37]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 0)

In [40]:
X_train.shape

(8000, 11)

In [41]:
X_test.shape

(2000, 11)

In [42]:
# scaling 

from sklearn.preprocessing import StandardScaler

In [43]:
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [44]:
X_train_trf

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [45]:
X_test_trf

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]])

In [67]:
# Initialize and train a binary classification model (Logistic Regression)
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_trf, y_train)

LogisticRegression()

In [68]:
# Make predictions on the testing set
y_pred = model.predict(X_test)

C:\Users\lenovo\anaconda3\Lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [69]:
# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
classification_report_str = classification_report(y_test, y_pred)

NameError: name 'classification_report' is not defined

In [48]:
#!pip install tensorflow

In [49]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [50]:
model = Sequential()

model.add(Dense(3,activation = "tanh",input_dim = 11))
model.add(Dense(1,activation  = "tanh"))

* model = Sequential()

This line creates a new Sequential model. This model is essentially an empty container for adding layers to it one by one. Think of it as a linear pipeline where data will flow through each layer in sequence.

* model.add(Dense(3, activation="sigmoid", input_dim=11))

    * This line adds the first layer to the model. Here's what each argument  means:

    * Dense(3, ...) defines a dense (fully connected) layer with 3 neurons (units) in this layer. The number of neurons in this layer is a hyperparameter that you can adjust based on your specific problem.

    * activation="sigmoid" sets the activation function for the neurons in this layer to the sigmoid function. The sigmoid activation function squashes the output of each neuron into the range (0, 1).

   * input_dim=11 specifies that the input to this layer has 11 dimensions. This is typically used in the first layer of the model to define the input shape. In this case, it suggests that the input data should have 11 features.
  
  
*  model.add(Dense(1, activation="sigmoid"))
     * This line adds a second dense layer to the model. Here's what it does:

    * Dense(1, ...) defines a dense layer with a single neuron. This is often used as the output layer in binary classification problems, where you're trying to predict one of two classes.

     * activation="sigmoid" sets the activation function for this output neuron to sigmoid as well. This is common in binary classification tasks because it produces an output in the range (0, 1), which can be interpreted as a probability.

In [51]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 3)                 36

 dense_1 (Dense)             (None, 1)                 4

=================================================================
Total params: 40 (160.00 Byte)
Trainable params: 40 (160.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [52]:
model.compile(loss = "binary_crossentropy" , optimizer ="Adam")

In [53]:
model.fit(X_train_trf , y_train , epochs = 50)

Epoch 1/50
250/250 [==============================] - 1s 2ms/step - loss: 1.4293
Epoch 2/50
250/250 [==============================] - 1s 2ms/step - loss: 1.3336
Epoch 3/50
250/250 [==============================] - 0s 2ms/step - loss: 1.2272
Epoch 4/50
250/250 [==============================] - 0s 2ms/step - loss: 1.1468
Epoch 5/50
250/250 [==============================] - 0s 2ms/step - loss: 1.0576
Epoch 6/50
250/250 [==============================] - 0s 2ms/step - loss: 1.0449
Epoch 7/50
250/250 [==============================] - 0s 2ms/step - loss: 1.0343
Epoch 8/50
250/250 [==============================] - 0s 2ms/step - loss: 1.0079
Epoch 9/50
250/250 [==============================] - 0s 2ms/step - loss: 0.9863
Epoch 10/50
250/250 [==============================] - 0s 2ms/step - loss: 0.9617
Epoch 11/50
250/250 [==============================] - 0s 2ms/step - loss: 0.9442
Epoch 12/50
250/250 [==============================] - 0s 2ms/step - loss: 0.9317
Epoch 13/50
250/250 [==============================] - 0s 2ms/step - loss: 0.9203
Epoch 14/50
250/250 [==============================] - 0s 2ms/step - loss: 0.9019
Epoch 15/50
250/250 [==============================] - 0s 2ms/step - loss: 0.8766
Epoch 16/50
250/250 [==============================] - 0s 2ms/step - loss: 0.8514
Epoch 17/50
250/250 [==============================] - 0s 2ms/step - loss: 0.8350
Epoch 18/50
250/250 [==============================] - 0s 2ms/step - loss: 0.8037
Epoch 19/50
250/250 [==============================] - 0s 2ms/step - loss: 0.7784
Epoch 20/50
250/250 [==============================] - 0s 2ms/step - loss: 0.7195
Epoch 21/50
250/250 [==============================] - 0s 2ms/step - loss: 0.6479
Epoch 22/50
250/250 [==============================] - 0s 2ms/step - loss: 0.5754
Epoch 23/50
250/250 [==============================] - 0s 2ms/step - loss: 0.5583
Epoch 24/50
250/250 [==============================] - 0s 2ms/step - loss: 0.5163
Epoch 25/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4930
Epoch 26/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4847
Epoch 27/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4744
Epoch 28/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4700
Epoch 29/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4672
Epoch 30/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4662
Epoch 31/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4637
Epoch 32/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4586
Epoch 33/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4516
Epoch 34/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4507
Epoch 35/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4538
Epoch 36/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4499
Epoch 37/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4479
Epoch 38/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4467
Epoch 39/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4474
Epoch 40/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4468
Epoch 41/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4475
Epoch 42/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4451
Epoch 43/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4440
Epoch 44/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4429
Epoch 45/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4424
Epoch 46/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4417
Epoch 47/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4408
Epoch 48/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4401
Epoch 49/50
250/250 [==============================] - 0s 2ms/step - loss: 0.4420
Epoch 50/50
250/250 [==============================] - 1s 2ms/step - loss: 0.4387

In [54]:
model.layers[0].get_weights()

[array([[ 0.08854102,  0.03415987,  0.57669014],
        [ 1.0098768 , -0.1579837 ,  0.3267873 ],
        [ 0.11410895, -0.06116702,  0.59257627],
        [-0.0113847 , -0.33557394,  0.00388469],
        [-0.11450741,  0.12756543, -0.24645849],
        [-0.28676066, -0.21820343, -0.64377344],
        [-0.08655924,  0.2955371 ,  0.23122753],
        [-0.09867369, -0.39542988,  0.2732753 ],
        [ 0.25996456, -0.14230084,  0.05438201],
        [-0.02209638,  0.22750026, -0.40434793],
        [-0.32187837, -0.26402012,  0.10684185]], dtype=float32),
 array([-0.07281482, -0.15673651, -0.08950075], dtype=float32)]

In [55]:
model.layers[1].get_weights()

[array([[ 0.20693637],
        [-0.06028448],
        [-0.05844756]], dtype=float32),
 array([0.22607827], dtype=float32)]

In [56]:
model.predict(X_test_trf)

# out is not in form or 0  and 1  because : we applied sugmoid function .

63/63 [==============================] - 0s 2ms/step

array([[0.2553157 ],
       [0.30590063],
       [0.27060243],
       ...,
       [0.14585307],
       [0.18535547],
       [0.126236  ]], dtype=float32)

In [57]:


y_log = model.predict(X_test_trf)

63/63 [==============================] - 0s 2ms/step

In [58]:
# to make output in form of 0 and 1 we take threshhold value (0.5)
y_pred = np.where(y_log>0.5 , 1,0)   

# values > 0.5 (threshold) is , 1 
# values < 0.5 (threshold ) is 0

In [59]:
# check accuracy 

from sklearn.metrics import accuracy_score
accuracy_score(y_test , y_pred)

0.7975

In [60]:
# we want to increase accuracy 

# epochs increse 
# layers increse
# activatin function change
#

In [61]:
model = Sequential()

model.add(Dense(3,activation = "relu",input_dim = 11))
model.add(Dense(1,activation  = "relu"))
model.add(Dense(1, activation = "sigmoid"))

In [62]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_2 (Dense)             (None, 3)                 36

 dense_3 (Dense)             (None, 1)                 4

 dense_4 (Dense)             (None, 1)                 2

=================================================================
Total params: 42 (168.00 Byte)
Trainable params: 42 (168.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [63]:
model.compile(loss ="binary_croosentropy" ,optimizer = "Adam" ,metrics = ["accuracy"])

In [64]:
y_log = model.predict(X_test_scaled)
y_pred = np.where()
history = model.fit(X_train_scaled , y_train , epochs = )

SyntaxError: invalid syntax (3620156955.py, line 3)